force-app/main/default/objects/FuzzyPicklist__mdt/FuzzyPicklist__mdt.object-meta.xml
<CustomObject>
    <label>FuzzyPicklist</label>
    <pluralLabel>FuzzyPicklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Free_Text_Field__c.field-meta.xml
<CustomField>
    <fullName>Free_Text_Field__c</fullName>
    <label>Free Text Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists</relationshipLabel>
    <relationshipName>FuzzyPicklists</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Match_Last_Evaluated_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Match_Last_Evaluated_Date_Time_Field__c</fullName>
    <label>Match Last Evaluated Date Time Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists2</relationshipLabel>
    <relationshipName>FuzzyPicklists2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists</relationshipLabel>
    <relationshipName>FuzzyPicklists</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Picklist_Field__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Field__c</fullName>
    <label>Picklist Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists1</relationshipLabel>
    <relationshipName>FuzzyPicklists1</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Text_Last_Populated_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Text_Last_Populated_Date_Time_Field__c</fullName>
    <label>Text Last Populated Date Time Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists3</relationshipLabel>
    <relationshipName>FuzzyPicklists3</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistPossibility__mdt/FuzzyPicklistPossibility__mdt.object-meta.xml
<CustomObject>
    <label>FuzzyPicklistPossibility</label>
    <pluralLabel>FuzzyPicklistPossibilities</pluralLabel>
</CustomObject>

force-app/main/default/objects/FuzzyPicklistPossibility__mdt/fields/FuzzyPicklistValue__c.field-meta.xml
<CustomField>
    <fullName>FuzzyPicklistValue__c</fullName>
    <label>FuzzyPicklistValue</label>
    <referenceTo>FuzzyPicklistValue__mdt</referenceTo>
    <relationshipLabel>FuzzyPicklistPossibilities</relationshipLabel>
    <relationshipName>FuzzyPicklistPossibilities</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistPossibility__mdt/fields/Match_String__c.field-meta.xml
<CustomField>
    <fullName>Match_String__c</fullName>
    <label>Match String</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistValue__mdt/FuzzyPicklistValue__mdt.object-meta.xml
<CustomObject>
    <label>FuzzyPicklistValue</label>
    <pluralLabel>FuzzyPicklistValues</pluralLabel>
</CustomObject>

force-app/main/default/objects/FuzzyPicklistValue__mdt/fields/FuzzyPicklist__c.field-meta.xml
<CustomField>
    <fullName>FuzzyPicklist__c</fullName>
    <description>The picklist that this match belongs to</description>
    <label>FuzzyPicklist</label>
    <referenceTo>FuzzyPicklist__mdt</referenceTo>
    <relationshipName>FuzzyPicklistValues</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistValue__mdt/fields/Picklist_API_Value__c.field-meta.xml
<CustomField>
    <fullName>Picklist_API_Value__c</fullName>
    <label>Picklist API Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FuzzyPicklists.cls
public class FuzzyPicklists {
    
    public static void matchAllPicklists(List<Id> recordIds){
        //find all MDTs for the object
        List<FuzzyPicklist__mdt> fps = getFuzzyPicklists(recordIds);
        system.debug(fps);
        //for each MDT, pass to matchPicklist
        List<sObject> recordsToUpdate = new List<sObject>();
        for(FuzzyPicklist__mdt fp : fps){
            recordsToUpdate.addAll(matchpicklist(fp, recordIds));
        }
        if(recordsToUpdate.size()>0 && recordsToUpdate != null){
            update recordsToUpdate;
        }
    }
    
    public static List<sObject> matchPicklist(FuzzyPicklist__mdt fp, List<id> recordIds){
        //find all relevant FuzzyPicklistValues
        List<FuzzyPicklistValue__mdt> fpvs = getFuzzyPicklistValues(fp);
        //find all relevant FuzzyPicklistPossibilities
        List<FuzzyPicklistPossibility__mdt> fpps = getFuzzyPicklistPossibilities(fpvs); 
        //find full info from all IDs with
        //dynamic soql assembling free text field and picklist field as defined in fp
        //this could be more scalable but works for now
        List<sObject> records = Database.query(buildBaseQueryString(fp)+' WHERE Id IN :recordIds');
        List<sObject> recordsToUpdate = new List<sObject>();
        //for each record
        for(sObject rec : records){
            //only process if text has updated since last evaluation
            //or if picklist is still null
            Boolean matchFound = false;
            if((DateTime)rec.get(fp.Text_Last_Populated_Date_Time_Field__r.QualifiedAPIName) > 
               (DateTime)rec.get(fp.Match_Last_Evaluated_Date_Time_Field__r.QualifiedAPIName)
               || (String)rec.get(fp.Picklist_Field__r.QualifiedAPIName) == null
               || (DateTime)rec.get(fp.Match_Last_Evaluated_Date_Time_Field__r.QualifiedAPIName) == null
              ){
                  //loop FuzzyPicklistPossibility records comparing string value
                  for(FuzzyPicklistPossibility__mdt fpp : fpps){
                      if((String)rec.get(fp.Free_Text_Field__r.QualifiedAPIName) == fpp.Match_String__c){
                          //when it matches
                          //loop FuzzyPicklistValue records comparing fpv.ID to fpp.fpv
                          matchFound = true;
                          for(FuzzyPicklistValue__mdt fpv : fpvs){
                              if(fpp.FuzzyPicklistValue__c == fpv.Id){
                                  //when it matches
                                  //write record.picklistvalue to FuzzyPicklistValue.picklistapivalue
                                  rec.put(fp.Picklist_Field__r.QualifiedAPIName,fpv.Picklist_API_Value__c);
                                  rec.put(fp.Match_Last_Evaluated_Date_Time_Field__r.QualifiedAPIName,System.now());
                                  recordsToUpdate.add(rec);
                              }
                          } 
                      } 
                  }
              }
            //if field has been updated and no match found to new value,
            //clear out picklist value so it can be re-qualified by a human.
            //may want this behind a setting.
            if(!matchFound 
               && (DateTime)rec.get(fp.Text_Last_Populated_Date_Time_Field__r.QualifiedAPIName) > 
               (DateTime)rec.get(fp.Match_Last_Evaluated_Date_Time_Field__r.QualifiedAPIName) 
               && (String)rec.get(fp.Picklist_Field__r.QualifiedAPIName) != null){
                   rec.put(fp.Picklist_Field__r.QualifiedAPIName,null);
                   rec.put(fp.Match_Last_Evaluated_Date_Time_Field__r.QualifiedAPIName,System.now());
                   recordsToUpdate.add(rec);
               }
        }
        return recordsToUpdate;
    }
    
    public static List<FuzzyPicklist__mdt> getFuzzyPicklists(List<Id> recordIds){
        return [SELECT Id
                , DeveloperName 
                , Object__c
                , Free_Text_Field__c
                , Picklist_Field__c
                , Match_Last_Evaluated_Date_Time_Field__c
                , Text_Last_Populated_Date_Time_Field__c
                , Free_Text_Field__r.QualifiedAPIName
                , Picklist_Field__r.QualifiedAPIName
                , Match_Last_Evaluated_Date_Time_Field__r.QualifiedAPIName
                , Text_Last_Populated_Date_Time_Field__r.QualifiedAPIName
                FROM FuzzyPicklist__mdt
                WHERE Object__c = :String.valueof(recordIds[0].getSObjectType())
               ];
        
    }
    
    public static List<FuzzyPicklistValue__mdt> getFuzzyPicklistValues(FuzzyPicklist__mdt fp){
        return [SELECT Id
                , DeveloperName
                , Picklist_API_Value__c
                , FuzzyPicklist__c
                FROM FuzzyPicklistValue__mdt
                WHERE FuzzyPicklist__c = :fp.Id];
    }
    
    public static List<FuzzyPicklistPossibility__mdt> getFuzzyPicklistPossibilities(List<FuzzyPicklistValue__mdt> fpvs){
        return [SELECT Id
                , DeveloperName
                , Match_String__c  
                , FuzzyPicklistValue__c
                FROM FuzzyPicklistPossibility__mdt
                WHERE FuzzyPicklistValue__c IN :fpvs];
    }
    
    public static String buildBaseQueryString(FuzzyPicklist__mdt fp){
        String query = 'SELECT Id, Name';
        query += ', '+fp.Picklist_Field__r.QualifiedAPIName;
        query += ', '+fp.Free_Text_Field__r.QualifiedAPIName;
        query += ', '+fp.Match_Last_Evaluated_Date_Time_Field__r.QualifiedAPIName;
        query += ', '+fp.Text_Last_Populated_Date_Time_Field__r.QualifiedAPIName;
        query += ' FROM '+fp.Object__c;
        system.debug(query);
        return query;
    }
    
}