force-app/main/default/objects/FuzzyPicklist__mdt/FuzzyPicklist__mdt.object-meta.xml
<CustomObject>
    <label>FuzzyPicklist</label>
    <pluralLabel>FuzzyPicklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Free_Text_Field__c.field-meta.xml
<CustomField>
    <fullName>Free_Text_Field__c</fullName>
    <label>Free Text Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists</relationshipLabel>
    <relationshipName>FuzzyPicklists</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Match_Last_Evaluated_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Match_Last_Evaluated_Date_Time_Field__c</fullName>
    <label>Match Last Evaluated Date Time Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists2</relationshipLabel>
    <relationshipName>FuzzyPicklists2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists</relationshipLabel>
    <relationshipName>FuzzyPicklists</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Picklist_Field__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Field__c</fullName>
    <label>Picklist Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists1</relationshipLabel>
    <relationshipName>FuzzyPicklists1</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Text_Last_Populated_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Text_Last_Populated_Date_Time_Field__c</fullName>
    <label>Text Last Populated Date Time Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists3</relationshipLabel>
    <relationshipName>FuzzyPicklists3</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistValue__mdt/FuzzyPicklistValue__mdt.object-meta.xml
<CustomObject>
    <label>FuzzyPicklistValue</label>
    <pluralLabel>FuzzyPicklistValues</pluralLabel>
</CustomObject>

force-app/main/default/objects/FuzzyPicklistValue__mdt/fields/FuzzyPicklist__c.field-meta.xml
<CustomField>
    <fullName>FuzzyPicklist__c</fullName>
    <description>The picklist that this match belongs to</description>
    <label>FuzzyPicklist</label>
    <referenceTo>FuzzyPicklist__mdt</referenceTo>
    <relationshipName>FuzzyPicklistValues</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistValue__mdt/fields/Picklist_API_Value__c.field-meta.xml
<CustomField>
    <fullName>Picklist_API_Value__c</fullName>
    <label>Picklist API Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CMDTMockProvider.cls
@isTest
public with sharing class CMDTMockProvider implements System.StubProvider {

    public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, 
        Type returnType, List<Type> listOfParamTypes, List<String> listOfParamNames, 
        List<Object> listOfArgs) {
        
        if (stubbedMethodName == 'getFuzzyPicklists') {
            return buildFP();
        } else if (stubbedMethodName == 'getFuzzyPicklistValuesWithPossibilities'){
            return buildFPValues();
        } else {
            return null;
        }
    }

    private Object buildFP() {
        String fpjson = '[{"Id":"fpID"';
        fpjson += ',"DeveloperName":"Test"';
        fpjson += ',"Object__c":"Contact"';
        fpjson += ',"Free_Text_Field__c":"Contact.Title"';
        fpjson += ',"Picklist_Field__c":"Contact.LeadSource"';
        fpjson += ',"Match_Last_Evaluated_Date_Time_Field__c":"Contact.LastModifiedDate"';
        fpjson += ',"Text_Last_Populated_Date_Time_Field__c":"Contact.CreatedDate"';
        fpjson += '}]';
        return (List<FuzzyPicklist__mdt>) JSON.deserialize(fpjson, List<FuzzyPicklist__mdt>.class );
    }

    private Object buildFPValues() {
        String fpvjson = '[{"Id":"fpv1Id"';
        fpvjson += ',"DeveloperName":"Web"';
        fpvjson += ',"Picklist_API_Value__c":"Web"';
        fpvjson += ',"FuzzyPicklist__c":"fpId"}';
        fpvjson += ',{"Id":"fpv2Id"';
        fpvjson += ',"DeveloperName":"Other"';
        fpvjson += ',"Picklist_API_Value__c":"Other"';
        fpvjson += ',"FuzzyPicklist__c":"fpId"';
        fpvjson += '}]';
        return (List<FuzzyPicklistValue__mdt>) JSON.deserialize(fpvjson, List<FuzzyPicklistValue__mdt>.class );
    }
}