force-app/main/default/objects/FuzzyPicklist__mdt/FuzzyPicklist__mdt.object-meta.xml
<CustomObject>
    <label>FuzzyPicklist</label>
    <pluralLabel>FuzzyPicklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Free_Text_Field__c.field-meta.xml
<CustomField>
    <fullName>Free_Text_Field__c</fullName>
    <label>Free Text Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists</relationshipLabel>
    <relationshipName>FuzzyPicklists</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Match_Last_Evaluated_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Match_Last_Evaluated_Date_Time_Field__c</fullName>
    <label>Match Last Evaluated Date Time Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists2</relationshipLabel>
    <relationshipName>FuzzyPicklists2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists</relationshipLabel>
    <relationshipName>FuzzyPicklists</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Picklist_Field__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Field__c</fullName>
    <label>Picklist Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists1</relationshipLabel>
    <relationshipName>FuzzyPicklists1</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklist__mdt/fields/Text_Last_Populated_Date_Time_Field__c.field-meta.xml
<CustomField>
    <fullName>Text_Last_Populated_Date_Time_Field__c</fullName>
    <label>Text Last Populated Date Time Field</label>
    <metadataRelationshipControllingField>FuzzyPicklist__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>FuzzyPicklists3</relationshipLabel>
    <relationshipName>FuzzyPicklists3</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistPossibility__mdt/FuzzyPicklistPossibility__mdt.object-meta.xml
<CustomObject>
    <label>FuzzyPicklistPossibility</label>
    <pluralLabel>FuzzyPicklistPossibilities</pluralLabel>
</CustomObject>

force-app/main/default/objects/FuzzyPicklistPossibility__mdt/fields/FuzzyPicklistValue__c.field-meta.xml
<CustomField>
    <fullName>FuzzyPicklistValue__c</fullName>
    <label>FuzzyPicklistValue</label>
    <referenceTo>FuzzyPicklistValue__mdt</referenceTo>
    <relationshipLabel>FuzzyPicklistPossibilities</relationshipLabel>
    <relationshipName>FuzzyPicklistPossibilities</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistPossibility__mdt/fields/Match_String__c.field-meta.xml
<CustomField>
    <fullName>Match_String__c</fullName>
    <label>Match String</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistValue__mdt/FuzzyPicklistValue__mdt.object-meta.xml
<CustomObject>
    <label>FuzzyPicklistValue</label>
    <pluralLabel>FuzzyPicklistValues</pluralLabel>
</CustomObject>

force-app/main/default/objects/FuzzyPicklistValue__mdt/fields/FuzzyPicklist__c.field-meta.xml
<CustomField>
    <fullName>FuzzyPicklist__c</fullName>
    <description>The picklist that this match belongs to</description>
    <label>FuzzyPicklist</label>
    <referenceTo>FuzzyPicklist__mdt</referenceTo>
    <relationshipName>FuzzyPicklistValues</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/FuzzyPicklistValue__mdt/fields/Picklist_API_Value__c.field-meta.xml
<CustomField>
    <fullName>Picklist_API_Value__c</fullName>
    <label>Picklist API Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CMDTUtil.cls
public with sharing class CMDTUtil {

    public List<FuzzyPicklist__mdt> getFuzzyPicklists(List<Id> recordIds){
        String obj = String.valueof(recordIds[0].getSObjectType());
        return [SELECT Id
                , DeveloperName 
                , Object__c
                , Free_Text_Field__c
                , Picklist_Field__c
                , Match_Last_Evaluated_Date_Time_Field__c
                , Text_Last_Populated_Date_Time_Field__c
                , Free_Text_Field__r.QualifiedAPIName
                , Picklist_Field__r.QualifiedAPIName
                , Match_Last_Evaluated_Date_Time_Field__r.QualifiedAPIName
                , Text_Last_Populated_Date_Time_Field__r.QualifiedAPIName
                FROM FuzzyPicklist__mdt
                WHERE Object__c = :obj
               ];
        
    }

    public List<FuzzyPicklistValue__mdt> getFuzzyPicklistValuesWithPossibilities(List<FuzzyPicklist__mdt> fps){  
        return [SELECT Id
                , DeveloperName
                , Picklist_API_Value__c
                , FuzzyPicklist__c
                , (SELECT Id
                   , DeveloperName
                   , Match_String__c  
                   , FuzzyPicklistValue__c
                   FROM FuzzyPicklistPossibilities__r)
                FROM FuzzyPicklistValue__mdt
                WHERE FuzzyPicklist__c IN :fps];
    }
}